[project]
name = "socks-tls-ping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["httpx[http2,socks]>=0.28.1"]

[project.optional-dependencies]
matplotlib = ["matplotlib>=3.10.8", "pyside6>=6.10.1"]
pyecharts = ["pyecharts>=2.0.9"]
fastplotlib = ["fastplotlib[imgui]", "glfw>=2.10.0", "numpy<2.4"]

[tool.setuptools]
packages = ["socks_tls_ping"]

[project.scripts]
socks-tls-ping = "socks_tls_ping.__main__:_main"
